---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-config
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: "1Gi"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-data
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  accessModes:
    - "ReadWriteOnce"
  {{- if .Values.persistence.storageClassName }}
  storageClassName: {{ .Values.persistence.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: "5Gi"
