---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    nodePort: 30053
    protocol: UDP
    name: dns-udp
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}
---
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  labels:
    {{- include "adguard-home.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    {{- include "adguard-home.selectorLabels" . | nindent 4 }}