---
# Source: adguard-home/templates/configmap.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: adguard-home-config
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
data:
  AdGuardHome.yaml: |
    bind_host: 0.0.0.0
    bind_port: 3000
    beta_bind_port: 0
    users: []
    auth_attempts: 5
    block_auth_min: 15
    http_proxy: ""
    language: ""
    debug_pprof: false
    web_session_ttl: 720
    dns:
      bind_hosts:
      - 0.0.0.0
      port: 53
      statistics_interval: 1
      querylog_enabled: true
      querylog_file_enabled: true
      querylog_interval: 2160h
      querylog_size_memory: 1000
      anonymize_client_ip: false
      protection_enabled: true
      blocking_mode: default
      blocking_ipv4: ""
      blocking_ipv6: ""
      blocked_response_ttl: 10
      parental_block_host: family-block.dns.adguard.com
      safebrowsing_block_host: standard-block.dns.adguard.com
      ratelimit: 20
      ratelimit_whitelist: []
      refuse_any: true
      upstream_dns:
      - https://dns10.quad9.net/dns-query
      upstream_dns_file: ""
      bootstrap_dns:
      - 9.9.9.10
      - 149.112.112.10
      - 2620:fe::10
      - 2620:fe::fe:10
      all_servers: false
      fastest_addr: false
      fastest_timeout: 1s
      allowed_clients: []
      disallowed_clients: []
      blocked_hosts:
      - version.bind
      - id.server
      - hostname.bind
      trusted_proxies:
      - 127.0.0.0/8
      - ::1/128
      cache_size: 4194304
      cache_ttl_min: 0
      cache_ttl_max: 0
      cache_optimistic: false
      bogus_nxdomain: []
      aaaa_disabled: false
      enable_dnssec: false
      edns_client_subnet: false
      max_goroutines: 300
      ipset: []
      filtering_enabled: true
      filters_update_interval: 24
      parental_enabled: false
      safesearch_enabled: false
      safebrowsing_enabled: false
      safebrowsing_cache_size: 1048576
      safesearch_cache_size: 1048576
      parental_cache_size: 1048576
      cache_time: 30
      rewrites: []
      blocked_services: []
      upstream_timeout: 10s
      private_networks: []
      use_private_ptr_resolvers: true
      local_ptr_upstreams: []
    tls:
      enabled: false
      server_name: ""
      force_https: false
      port_https: 443
      port_dns_over_tls: 853
      port_dns_over_quic: 853
      port_dnscrypt: 0
      dnscrypt_config_file: ""
      allow_unencrypted_doh: false
      strict_sni_check: false
      certificate_chain: ""
      private_key: ""
      certificate_path: ""
      private_key_path: ""
    filters:
    - enabled: true
      url: https://adguardteam.github.io/AdGuardSDNSFilter/Filters/filter.txt
      name: AdGuard DNS filter
      id: 1
    - enabled: false
      url: https://adaway.org/hosts.txt
      name: AdAway Default Blocklist
      id: 2
    whitelist_filters: []
    user_rules: []
    dhcp:
      enabled: false
      interface_name: ""
      local_domain_name: lan
      dhcpv4:
        gateway_ip: ""
        subnet_mask: ""
        range_start: ""
        range_end: ""
        lease_duration: 86400
        icmp_timeout_msec: 1000
        options: []
      dhcpv6:
        range_start: ""
        lease_duration: 86400
        ra_slaac_only: false
        ra_allow_slaac: false
    clients:
      runtime_sources:
        whois: true
        arp: true
        rdns: true
        dhcp: true
        hosts: true
      persistent: []
    log_compress: false
    log_localtime: false
    log_max_backups: 0
    log_max_size: 100
    log_max_age: 3
    log_file: ""
    verbose: false
    statistics:
      enabled: true
      interval: 30d
    os:
      group: ""
      user: ""
      rlimit_nofile: 0
    schema_version: 14
---
# Source: adguard-home/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-config
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: longhorn
  resources:
    requests:
      storage: "1Gi"
---
# Source: adguard-home/templates/pvc.yaml
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: adguard-home-data
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  accessModes:
    - "ReadWriteOnce"
  storageClassName: longhorn
  resources:
    requests:
      storage: "5Gi"
---
# Source: adguard-home/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-tcp
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    protocol: TCP
    name: dns-tcp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
---
# Source: adguard-home/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home-dns-udp
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  type: NodePort
  externalTrafficPolicy: Local
  ports:
  - port: 53
    targetPort: 53
    nodePort: 5353
    protocol: UDP
    name: dns-udp
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
---
# Source: adguard-home/templates/service.yaml
apiVersion: v1
kind: Service
metadata:
  name: adguard-home
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
---
# Source: adguard-home/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adguard-home
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app.kubernetes.io/name: adguard-home
      app.kubernetes.io/instance: adguard-home
  template:
    metadata:
      labels:
        app.kubernetes.io/name: adguard-home
        app.kubernetes.io/instance: adguard-home
    spec:
      nodeSelector:
        kubernetes.io/hostname: homelab-node0
      initContainers:
        - command:
          - sh
          - -c
          - |
            if [ ! -f /opt/adguardhome/conf/AdGuardHome.yaml ]; then
              mkdir -p /opt/adguardhome/conf
              cp /tmp/AdGuardHome.yaml /opt/adguardhome/conf/AdGuardHome.yaml
            fi
          image: busybox
          imagePullPolicy: IfNotPresent
          name: copy-configmap
          securityContext:
            runAsUser: 0
          volumeMounts:
          - mountPath: /tmp/AdGuardHome.yaml
            name: adguard-home-config
            subPath: AdGuardHome.yaml
          - mountPath: /opt/adguardhome/conf
            name: config
      containers:
        - name: adguard-home
          image: "adguard/adguardhome:v0.107.34"
          imagePullPolicy: IfNotPresent
          command: ["/opt/adguardhome/AdGuardHome"]
          args:
            - --config
            - /opt/adguardhome/conf/AdGuardHome.yaml
            - --work-dir
            - /opt/adguardhome/work
            - --no-check-update
          env:
            - name: TZ
              value: EEST
          ports:
            - name: dns-tcp
              containerPort: 53
              protocol: TCP
            - name: dns-udp
              containerPort: 53
              protocol: UDP
            - name: http
              containerPort: 3000
              protocol: TCP
          volumeMounts:
            - name: adguard-home-config
              mountPath: /tmp/AdGuardHome.yaml
              subPath: AdGuardHome.yaml
            - name: config
              mountPath: /opt/adguardhome/conf
            - name: data
              mountPath: /opt/adguardhome/work
          livenessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          readinessProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 3
            timeoutSeconds: 1
            periodSeconds: 10
          startupProbe:
            tcpSocket:
              port: 3000
            initialDelaySeconds: 0
            failureThreshold: 30
            timeoutSeconds: 1
            periodSeconds: 5
      volumes:
        - name: adguard-home-config
          configMap:
            name: adguard-home-config
        - name: config
          persistentVolumeClaim:
            claimName: adguard-home-config
        - name: data
          persistentVolumeClaim:
            claimName: adguard-home-data
---
# Source: adguard-home/templates/ingress.yaml
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: adguard-home
  labels:
    helm.sh/chart: adguard-home-1.4.0
    app.kubernetes.io/name: adguard-home
    app.kubernetes.io/instance: adguard-home
    app.kubernetes.io/version: "v0.107.34"
    app.kubernetes.io/managed-by: Helm
  annotations:
    external-dns.alpha.kubernetes.io/exclude: "true"
spec:
  ingressClassName: nginx
  rules:
  - host: adguard.vmotso.cloud
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: adguard-home
            port:
              name: http
